name: deploy-ke-vps

on: 
  push:
    branches:
      - main

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project ke VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd ci_cd_learn
            git pull origin main
            echo "Berhasil deploy ke VPS coy"
