name: elysia basic test

on: 
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v2
      - name: install depedency
        run: bun install
      - name: lint & quality code
        run: bun lint
      - name: testing
        run: bun test
